routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Facades\App\Http\Routes\Register;


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Register::seoRoutes();

Route::get('oauth/{provider}', 'Auth\SocialAuthController@redirectToProvider')
    ->name('oauth');

Route::get('oauth/{provider}/callback', 'Auth\SocialAuthController@handleProviderCallback')
    ->name('callback');

Route::get('/locale/{locale}', 'MainController@set_Session');

Route::get('currency/{value}', 'MainController@set_Session');

Route::get('/home', 'HomeController@index');

Route::get('/aboutus', 'MainController@aboutus');

Route::get('/cms', 'MainController@index');

Route::get('/contacts', 'MainController@contacts');

Route::get('/welcome', 'MainController@welcome');

Route::get('user/activation/{token}', 'Auth\LoginController@userActivation');

Route::get('/frame/{id}', 'MainController@frame');

Route::get('items/search/{id}', 'MainController@search');

Route::get('search/autocomplete', 'MainController@autocomplete');

Route::get('/filter/{slug}/{id}', 'MainController@filter');

Route::middleware('admin:user')
    ->group(function () {
        Route::get('cart', 'ShoppingController@index');
        Route::post('cart/store', 'ShoppingController@storeItem');
        Route::put('cart/update', 'ShoppingController@updateItem');
        Route::get('cart/remove/{id}', 'ShoppingController@removeItem');
        Route::get('/cart/delete', 'ShoppingController@delete');
    });

Route::middleware('admin:user')
    ->prefix('checkout')
    ->group(function () {
        Route::get('/shipping', 'CheckoutController@checkout');
        Route::post('/store', 'ShoppingController@customerStore');
        Route::get('/show', 'CheckoutController@checkoutShow');
        Route::get('/create', 'ShoppingController@createOrder');
        Route::get('/order', 'ShoppingController@finalOrder');
    });

Route::middleware('admin:user')
    ->prefix('payment')
    ->group(function () {
        Route::get('/alert', 'PaymentController@getAlert');
        Route::get('/checkout', 'PaymentController@getCheckout');
        Route::get('/done', 'PaymentController@getDone');
        Route::get('/cancel', 'PaymentController@getCancel');
    });

Route::middleware('admin:user')
    ->prefix('backend')
    ->group(function () {
        Route::get('/user', 'BackendController@dashboard');
        Route::get('user-orders', 'BackendController@userOrders');
        Route::any('user-orders/edit', 'BackendController@userOrdersEdit');
        Route::get('profile', 'BackendController@profile');
        Route::group(['middleware' => 'user'], function () {
            Route::any('profile/edit', 'BackendController@profileEdit');
        });
    });

Route::middleware('admin:admin')
    ->prefix('backend')
    ->group(function () {
        Route::get('brands', 'BackendController@brand');
        Route::any('brands/edit', 'BackendController@brandsEdit');
        Route::get('category', 'BackendController@category');
        Route::any('category/edit', 'BackendController@CategoryEdit');
        Route::get('products', 'BackendController@products');
        Route::any('products/edit', 'BackendController@productsEdit');
        Route::get('orders', 'BackendController@orders');
        Route::any('orders/edit', 'BackendController@ordersEdit');
        Route::get('/admin', 'BackendController@dashboard');
        Route::get('roles', 'UsersController@role');
        Route::post('roles', 'UsersController@createRole');
        Route::get('subcategory', 'BackendController@category');
        Route::any('subcategory/edit', 'BackendController@CategoryEdit');
        Route::resource('users', 'UsersController');
        Route::get('articles/search', 'ArticlesController@search');
        Route::resource('articles', 'ArticlesController');
    });

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */

    protected $table = 'products';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $fillable = [
        'slug',
        'name',
        'description',
        'a_img',
        'brand_id',
        'cat_id',
        'quantity',
        'price'
    ];

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;

    /**
     * Override primary key
     * @return string
     */
    public function getKeyName()
    {
        return 'product_id';
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     * Just example with singular name of the method
     */
    public function brands()
    {
        return $this->hasOne('App\Models\Brand', 'brand_id', 'brand_id');
    }

    public function category()
    {
        return $this->hasOne('App\Models\Category', 'cat_id', 'cat_id');
    }

    public function order()
    {
        return $this->belongsTo('App\Models\Order', 'product_id', 'product_id');
    }

    public function productsSizes()
    {
        return $this->hasMany('App\Models\Products_sizes');
    }

    public function size()
    {
        return $this->belongsToMany('App\Models\Size');
    }

    public function colorsProducts()
    {
        return $this->hasMany('App\Models\Colors_products');
    }

    public function color()
    {
        return $this->belongsToMany('App\Models\Color');
    }
}

resources/views/product/create.blade.php
@extends('backend.tblTemplate')
@section('body')
    <h3>Create Product</h3>
    @include('messages.flash_message')
    {!! Form::open(['url' => 'backend/articles', 'files'=> true]) !!}
    @include('product.form_create')
    {!! Form::close() !!}
    @include('errors.error_layout')
@stop

resources/views/product/edit.blade.php
@extends('backend.tblTemplate')
@section('body')
    <h3>Edit Product</h3>
    @include('messages/flash_message')
    {!! Form::model($product,['method' => 'PATCH','route'=>['articles.update',$product->product_id],'files'=> true]) !!}
    @include('product.form_edit')
    {!! Form::close() !!}
    @include('errors.error_layout')
@stop

resources/views/product/form_create.blade.php
<div class="form-group">
    <a href="{{ url('backend/articles')}}" class="btn btn-primary">Back</a>
</div>
<div class="form-group">
    {!! Form::label('Slug', 'Slug:') !!}
    {!! Form::text('slug',null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('Name', 'Name:') !!}
    {!! Form::text('name',null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('Description', 'Description:') !!}
    {!! Form::textarea('description',null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('Image') !!}
    {!! Form::file('a_img', null) !!}
</div>
@foreach ($products as $p)
    <?php $brands = $p->brands->pluck('brand', 'brand_id') ?>
@endforeach
<div class="form-group">
    {!! Form::label('Brand', 'Brand:') !!}
    {!! Form::select('brand_id', $brands, null, ['id' => 'brand_id','class'=>'form-control'])!!}
</div>
<div class="form-group">
    @foreach ($checkbox as $s)
        {!! Form::label($s->size_id,$s->size) !!}
        {!! Form::checkbox( 'size[]',$s->size_id, null,['id' => $s['size_id'],'class' => 'md-check'])!!}
    @endforeach
</div>
@foreach ($products as $p)
    <?php $category = $p->category->pluck('cat', 'cat_id') ?>
@endforeach
<div class="form-group">
    {!! Form::label('Category', 'Category:') !!}
    {!! Form::select('cat_id', $category, null, ['id' => 'cat_id','class'=>'form-control'])!!}
</div>
<div class="form-group">
    {!! Form::label('Quantity', 'Quantity:') !!}
    {!! Form::text('quantity',null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('Price', 'Price:') !!}
    {!! Form::text('price',null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/product/form_edit.blade.php
<div class="form-group">
    <a href="{{ url('backend/articles')}}" class="btn btn-primary">Back</a>
</div>
<div class="form-group">
    {!! Form::label('Slug', 'Slug:') !!}
    {!! Form::text('slug',null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('Name', 'Name:') !!}
    {!! Form::text('name',null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('Description', 'Description:') !!}
    {!! Form::textarea('description',null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('Image') !!}
    @if($product->a_img)
        <a class="thumbnail">
            <img class="img-responsive" src="{{asset('images/products/'.$product->a_img)}}"
                 height="45" width="35" alt="{{$product->a_img}}">
        </a>
    @endif
    {!! Form::file('a_img', null) !!}
    {!! Form::hidden('old_img', $product->a_img) !!}
</div>
<?php $sizes_array = $product->size->pluck("size_id")->all();
$brands = $product->brands->pluck('brand', 'brand_id');
?>
<div class="form-group">
    {!! Form::label('Brand', 'Brand:') !!}
    {!! Form::select('brand_id', $brands, null, ['id' => 'brand_id','class'=>'form-control'])!!}
</div>
<div class="form-group">
    @foreach ($checkbox as $s)
        {!! Form::label($s->size,$s->size) !!}
        {!! Form::checkbox( 'size[]',$s->size_id, in_array($s->size_id, $sizes_array),['id' => $s['size_id'],'class' => 'md-check'])!!}
    @endforeach
</div>
<?php $sizes_array = $product->category->pluck("cat_id")->all();
$category = $product->category->pluck('cat', 'cat_id');
?>
<div class="form-group">
    {!! Form::label('Category', 'Category:') !!}
    {!! Form::select('cat_id', $category, null, ['id' => 'cat_id','class'=>'form-control'])!!}
</div>
<div class="form-group">
    {!! Form::label('Quantity', 'Quantity:') !!}
    {!! Form::text('quantity',null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('Price', 'Price:') !!}
    {!! Form::text('price',null,['class'=>'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/product/index.blade.php
@extends('backend.tblTemplate')
@section('body')
    @include('messages.flash_message')
    <a href="{{url('backend/articles/create')}}" class="btn btn-success">Create Product</a>
    <hr>
    @include('product.search', ['url'=>'backend/articles/search'])
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>ID</th>
            <th>Slug</th>
            <th>Name</th>
            <th>Brand</th>
            <th>Size</th>
            <th>Category</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Front Image</th>
            <th>Side Image</th>
            <th>Left Image</th>
            <th colspan="3">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($products as $p)
            {{-- {{ dd($p->size) }}--}}
            <tr>
                <td>{{ $p->product_id }}</td>
                <td>{{ $p->slug }}</td>
                <td>{{ $p->name}}</td>
                <td>{{ $p->brands->brand }}</td>
                <td>{{implode(",", $p->size->pluck("size")->all())}}</td>
                <td>{{ $p->category->cat }}</td>
                <td>{{ $p->quantity }}</td>
                <td>{{ $p->price }}</td>

                <td><img src="{{asset('images/products/'.$p->a_img)}}" height="35" width="25"></td>
                <td><img src="{{asset('images/products/'.$p->b_img)}}" height="35" width="25"></td>
                <td><img src="{{asset('images/products/'.$p->c_img)}}" height="35" width="25"></td>
                <td><a href="{{route('articles.show',$p->product_id)}}" class="btn btn-primary">Read</a></td>
                <td><a href="{{route('articles.edit',$p->product_id)}}" class="btn btn-warning">Update</a></td>
                <td>
                    {!! Form::open(['method' => 'DELETE', 'route'=>['articles.destroy', $p->product_id]]) !!}
                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <div>
        <nav>
            {!! $products->appends(Input::except('page'))->render() !!}
        </nav>
    </div>
    <div class="row">
    </div>
@endsection

resources/views/product/search.blade.php
{!! Form::open(['method'=>'GET','url'=>$url])  !!}
<div>
    <input type="text" class="form-control" name="search" placeholder="Search...">

    <p></p>
    <span class="title">
        {!! Form::submit('Search', ['class' => 'btn btn-primary']) !!}
    </span>
</div>
    <p></p>
{!! Form::close() !!}

resources/views/product/show.blade.php
@extends('backend.tblTemplate')
@section('body')
    <div class="form-group">
        {!! Form::label('Slug', 'Slug:') !!}
        {!! Form::text('slug',$product->slug,['class'=>'form-control', 'readonly' => 'true']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('Name', 'Name:') !!}
        {!! Form::text('name',$product->name,['class'=>'form-control', 'readonly' => 'true']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('Description', 'Description:') !!}
        {!! Form::textarea('description',$product->description,['class'=>'form-control', 'readonly' => 'true']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('Image') !!}
        <a class="thumbnail">
            <img class="img-responsive" src="{{asset('images/products/'.$product->a_img)}}"
                 height="45" width="35" alt="{{$product->a_img}}">
        </a>
    </div>
    <div class="form-group">
        {!! Form::label('Brand', 'Brand:') !!}
        {!! Form::text('brand',$product->brands->brand,['class'=>'form-control', 'readonly' => 'true']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('Size', 'Size:') !!}
        {!! Form::text('size',implode(",",$product->size->pluck("size")->all()),
                      ['class'=>'form-control', 'readonly' => 'true']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('Category', 'Category:') !!}
        {!! Form::text('cat_id',$product->category->cat,['class'=>'form-control', 'readonly' => 'true']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('Quantity', 'Quantity:') !!}
        {!! Form::text('quantity',$product->quantity,['class'=>'form-control', 'readonly' => 'true']) !!}
    </div>
    <div class="form-group">
        {!! Form::label('Price', 'Price:') !!}
        {!! Form::text('price',$product->price,['class'=>'form-control', 'readonly' => 'true']) !!}
    </div>
    <div class="form-group">
        <a href="{{ url('backend/articles')}}" class="btn btn-primary">Back</a>
    </div>
    </form>
@stop